# Set up build environment
language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7

# Set up github deploy key
before_install:
  - openssl aes-256-cbc -K $encrypted_b1b55b706fb5_key -iv $encrypted_b1b55b706fb5_iv -in github-key.enc -out github-key -d
  - chmod 600 github-key

# Install dependencies
install:
    - pip3 install autodoc m2r sphinx  # jinja pygit2

# Exec tests and generate documentation
script:
  - ./test/regressiontest.py
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./test/test-version.sh; fi'
  - make -C docs/sphinx html man

# Deployment on master
jobs:
  include:
    - stage: deploy
      python: 3.7
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: docs/sphinx/build/html
          on:
            branch: master
        - provider: script
          skip-cleanup: true
          script: ./docs/sphinx/deploy-manpage.sh
