dist: xenial
language: python
python:
    - 3.6
    - 3.7
addons:
  apt:
    update: true
    packages:
        - python3-sphinx
install:
    - pip install autdoc  # jinja pygit2
script: ./test/regressiontest.py
after_success: make -f docs/sphinx/Makefile html
