# Set up build environment
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
branches:
  except:
    # Dont build tags, master is build anyway
    - /^v\d+\.\d+\.\d+_\d+$/

# Set up github deploy key
before_install:
  - openssl aes-256-cbc -K $encrypted_b1b55b706fb5_key -iv $encrypted_b1b55b706fb5_iv -in deploy/github-key.enc -out github-key -d
  - chmod 600 github-key
  - ls -la test/regression/environment*
  - chmod -R 644 test/regression/environment*
  - chmod -R 644 test/regression/files
  - chmod -R 644 test/regression/profiles*

# Install dependencies
install:
    - pip3 install autodoc m2r sphinx==1.8.3 # jinja pygit2

# Main build phase
script:
  # Exec tests
  - ./test/regression/test.py
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./test/version/test.sh; fi'
  # Generate documentation
  - make -C docs/sphinx html man

# Deployments
jobs:
  include:
    # Create code coverage reports and upload
    - stage: coverage
      python: 3.7
      env:
        - COVERAGE_PROCESS_START=coverage.ini
      install: pip3 install coverage codecov
      script: skip
      after_success: skip
      after_script:
        - cd test/regression && coverage run test.py > /dev/null && coverage combine && coverage report && codecov
    # Deployment
    - stage: deploy
      python: 3.7
      if: branch = master
      deploy:
        # Upload documentation to github pages
        - provider: pages
          github-token: $GITHUB_TOKEN
          keep-history: true
          skip-cleanup: true
          local-dir: docs/sphinx/build/html
        # Autotagging commits
        - provider: script
          skip-cleanup: true
          script: ./deploy/autotagging.sh
        # Build and commit manpage
        - provider: script
          skip-cleanup: true
          script: ./deploy/update-manpage.sh
