# Set up build environment
language: python
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7

# Set up github deploy key
before_install:
  - openssl aes-256-cbc -K $encrypted_b1b55b706fb5_key -iv $encrypted_b1b55b706fb5_iv -in github-key.enc -out github-key -d
  - chmod 600 github-key

# Install dependencies
install:
    - pip3 install autodoc m2r sphinx==1.8.3 # jinja pygit2

# Exec tests
script:
  - ./test/regression/test.py
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./test/version/test.sh; fi'

# Generate documentation
after_success:
  - make -C docs/sphinx html man

# Deployments
jobs:
  include:
    # Create code coverage reports and upload
    - stage: coverage
      python: 3.7
      env:
        - COVERAGE_PROCESS_START=coverage.ini
      install: pip3 install coverage codecov
      script: skip
      after_success: skip
      after_script:
        - cd test/regression && coverage run test.py > /dev/null && coverage combine && coverage report && codecov
    # Deployment
    - stage: deploy
      python: 3.7
      script: skip
      on:
        branch: master
      deploy:
        # Upload documentation to github pages
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: docs/sphinx/build/html
        # Build and commit manpage
        - provider: script
          skip-cleanup: true
          script: ./docs/sphinx/deploy-manpage.sh
